language: python
python:
  - 3.8
  - 3.7
  - 3.6

install: pip install -U tox-travis

script: make test-all

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  on:
    tags: true
    repo: AndreMiras/eth-accounts
    python: 3.8
